server:
  port: 8761

spring:
  application:
    name: service-discovery

eureka:
  client:
    #eureka 서버에 등록하지 않음
    register-with-eureka: false
    #eureka 서버에 정보를 가져오지 않음
    fetch-registry: false